Professed: dashperms.class.professed
Alicorn: dashperms.class.alicorn
Bat Pony: dashperms.class.batpony
Changeling: dashperms.class.changeling
Earth Pony: dashperms.class.earthpony
Pegasus: dashperms.class.pegasus
Sea Pony: dashperms.class.seapony
Unicorn: dashperms.class.unicorn
Zebra: dashperms.class.zebra